### ISSUE TITLE
cursor appearing on line beneath text.

### ISSUE THREAD

**Issue by laurencefass** [mattboldt/typed.js#108]
All appears to be working fine but the cursor is appearing after a line break not after the last character.

>> output
Sed at diam ut justo pulvinar pellentesque vel ut metus. Quisque massa nunc.
|
>> end output

... my source html

<div class="typed-strings">
<p>Cras risus erat, semper bibendum arcu sit amet, porttitor scelerisque erat</p> 
<p>Sed at diam ut justo pulvinar pellentesque vel ut metus. Quisque massa nunc.</p></div>
<div id="typed"></div>

(firefox only) css

.typed-cursor{
    opacity: 1;
    animation: blink 0.7s infinite;
}
@keyframes blink{
    0% { opacity:1; }
    50% { opacity:0; }
    100% { opacity:1; }
}

**Comment by kylemclaren** [comment]
@laurencefass this issue is relevant: https://github.com/mattboldt/typed.js/issues/100

**Comment by donaldrelliott** [comment]
@laurencefass That issue pops up when using the <div class="element></div>. For me it went away by changing it to <span class="element"></span>. Once I took a look at the javascript file I figured that was the correct way to input it. Hope that helps you out. Take care.

**Comment by laurencefass** [comment]
many thanks.

**Comment by ethanpil** [comment]
Some more information on this issue. It looks like its an issue with block elements.

I had `<div>` which I switched to a `<span>` due to the above problem. Later, i added `display: block;` in the CSS on the span element and the issue returned. Also persists with `display: inline-block;` and the issue goes away when these properties are removed.

**Comment by raimondi1337** [comment]
I fixed this buy applying `width: auto;` to the div.

**Comment by crlang44** [comment]
You can also set the div to `display: inline;` This worked for me. Hope it helps someone else.

**Comment by HawiCaesar** [comment]
raimondi1337 I tried that and it seems not work. I just went back to with the span tag

**Comment by akanksha1999** [comment]
.wraper{
    top: 50%;
    left: 50%;
    transform: translate(-50%,-50%);
    position: absolute;
    width:auto;
    height: auto;
    text-align:center;
    white-space: nowrap;

 }
 .wraper ::after{

    content:'|';
    animation: blink 0.7s infinite;
}
.wraper h1{
    display:inline-block;
}
.typed-cursor
{
    display: inline;
    opacity: 1;
    animation: blink 0.7s infinite;
}
/* i have created a div tag named wraper and text to be dispalyed is written inside a span tag everythin is working fine but an additional cusor is being displayed on next line hoe to remove it.*/

**Comment by kaspar-allenbach** [comment]
I want to add that this also happens when your parent element is a flexbox model

**Comment by NicolasPL64** [comment]
![Image](https://github.com/user-attachments/assets/9f46350f-ee64-4a73-b15e-d4bede33d7a5)

```
<template>
  <div style="display: inline; inline-size: auto" id="typed-element">
    <span v-html="data"></span>
  </div>
  <span ref="typingElement"></span>
</template>
```
_Vue 3 code. I'm using a Ref for the data since it's retrieved from a fetch method._

Also happening to me, I've tried changing the `<div>` to `<span>` and nothing, also adding the styles said eariler and still nothing.
Any solutions?
