### ISSUE TITLE
Fade out each typed string not working correctly

### ISSUE THREAD

**Issue by ykushev** [mattboldt/typed.js#133]
Fade out each typed string not worked correctly with "stringsElement" and "loop". :worried:
[https://jsfiddle.net/xre0qf5v/4/](https://jsfiddle.net/xre0qf5v/4/)

**Comment by GeorgioWan** [comment]
Dear @ykushev ,

I think the problem happened here:
```javascript
if (curStrPos <= self.stopNum) {
  clearTimeout(clear);
  var clear = self.arrayPos = self.arrayPos + 1;
            
  // must pass new array position in this instance
  // instead of using global arrayPos
  self.typewrite(self.strings[self.arrayPos], curStrPos);
}
```
Take this code for ex, when you done the `backspace` second sentence (here now is **self.strings[1]**), but you still run `var clear = self.arrayPos = self.arrayPos + 1;`, then, you'll get error when you run `typewrite(self.strings[self.arrayPos], curStrPos);`, cause the **self.strings.length** here only for **2** ! 

Maybe you can try 
```javascript
if (self.arrayPos < self.strings.length - 1)
  self.arrayPos++;
else
  self.arrayPos = 0;
```
instead of `var clear = self.arrayPos = self.arrayPos + 1;`


https://jsfiddle.net/xre0qf5v/6/
:smiley:

**Comment by ykushev** [comment]
@GeorgioWan , thank you! it really works. Maybe need to edit wiki: https://github.com/mattboldt/typed.js/wiki

**Comment by GeorgioWan** [comment]
OKAY! update into wiki.
