### ISSUE TITLE
Writing whole texts with different styles

### ISSUE THREAD

**Issue by robincollin** [mattboldt/typed.js#181]
Hey, I'm right now trying to let my website look like writing an e-mail (e-mail developer here 👋🏽).

Is there a way to write whole texts with different styles with the stringElement-method?

The things I'm writing kind of look like this:

Note: I know that normally there can't be a `h2` in a `p-tag`.

![image](https://cloud.githubusercontent.com/assets/13996221/17983278/0b2930c8-6b0c-11e6-86be-06c3cd1832bc.png)

**Comment by michaelReyder** [comment]
I'm trying to do a similar thing, but with PrimJS. I'm guessing because prism already ran without finding any content, when it gets injected into the <code> tag it doesn't affect how prism displays it. If you're looking for syntax highlighting definitely take a look at PrismJS or HighlightJS. They'll take care of that. But I don't think it can be used in conjunction with typed.js without doing some custom modifications.
