### ISSUE TITLE
How to style p in #typed-strings and add different colors for the different p

### ISSUE THREAD

**Issue by lawrobi** [mattboldt/typed.js#197]

**Comment by atgeorgekary** [comment]
Whenever you open a paragraph tag in your HTML content for typed.js (strings:), instead of:

strings: ["<p>need to style this</p>"]

Do:

strings: ["<p class='green-class' id='typed-strings'>need to style this</p>"]

Alternatively, you can add styling through your parent element, such as #myTypedContainer p.

**Comment by rrtigga** [comment]
Why is this not closed?

**Comment by rrtigga** [comment]
Oh because it doesn't work
