### ISSUE TITLE
Mobile issues - need to keep the typed content in container

### ISSUE THREAD

**Issue by kylejburt** [mattboldt/typed.js#230]
I have an issue with type.js pushing and pulling the content below on mobile. This is not a fault of typed, but I am trying to figure out how to keep it contained. Using Divi on Wordpress - www.CatchSP.com

Thanks for the help in advance!

**Comment by PrayersAndApples** [comment]
Hi Kyle,

Have you made any progress with this?

I also need to keep typed within a container. would like to recreate the effect of typing (ith typed.js)  a typewriter ( background image)identical to the effect achieved at: htp://www.stephanemartinw.com/. However, I've struggled to find a way that's also mobile responsive.

The closest I've come is with: 

`.home-featured .home-widgets-1 {
    display: inline-block;
    display: table-cell;
    vertical-align: middle;
    width: 100%;
    padding: 200px 0;
    font-size: 20px;
    background: url(
http://littleoneslittlewords.com/wp-content/uploads/2017/04/Sample.jpg) no-repeat;
    width: 1000px;
}`

But the image is not completely mobile responsive (I need it to re-size exactly with the text) and the two items (text and image) are still separate - I need to figure out a way to configure this so the text takes places EXACTLY within a designated area (i.e., the paper on the typewriter).

I'm not sure what image to upload because I don't know exactly where it needs to go; however, this seems like the simplest of my problems at this point!

Anyways, thought it was worth reaching out - I'm going to scan through earlier threads and see if I can find anything, as well!

Thanks!

(My website is: http://littleoneslittlewords.com/)

**Comment by mattboldt** [comment]
This is more of a CSS issue
