### ISSUE TITLE
I can't get it to work on my rails app. 

### ISSUE THREAD

**Issue by MicheleSaba** [mattboldt/typed.js#249]
I've tried a bunch of different ways and I can't get it to work.
Is there a special way it needs to be plugged in to a rails app?
Does a one-page navigation bar have anything to do with it?

**Comment by Orlandster98** [comment]
@MicheleSaba I'm not familiar with rails. But it should not matter which frontend framework you choose. Just the way you include it can be different. Please also check if the file gets included or not (in the developer tools). Also check if jQuery is included. Otherwise you can also check the console for some errors.

**Comment by mattboldt** [comment]
It all depends on how you're importing assets to the app. Are you using a bower rails gem, or just copying the source into your project?

Either way, once you have that ironed out, the code should work just the same as any webpage (jquery or no jquery).

**Comment by MicheleSaba** [comment]
I got it! 👍
