### ISSUE TITLE
Improve line wrap for long words.

### ISSUE THREAD

**Issue by nickluger** [mattboldt/typed.js#330]
### Description

A long word gets typed at line number 1. When the word does not fit into line 1, (the line runs out of space), the words is moved over to line 2. 

Would it be possible that typed.js anticipates this behaviour by knowing beforehand how long the next word will be, and jumping to the next line **before** typing the long word. So UX doesn't suffer from a sudden "teleport" of the word into the next line.

### Demo
Works with every long word.

**Expected behavior:** [What you expect to happen]

Oh there comes a long word! I don't think it will fit here. Let's switch to the next line.

**Actual behavior:** [What actually happens]

Let's start typing this word .... damn it doesn't fit... ok let's just teleport it into the next line. Who cares about eye strain on the user side.. 🤩  

I know there are manual line breaks, but that gets very complicated on different screen sizes or when using i18n.

**Comment by nikosgatzoulis** [comment]
There may be an issue with such implementation. What if the viewport size changes again? Should it move the word back into its proper position or should it maintain the current position provided that your behaviour is implemented.

**Example** (768x1024 [out of maximum 1080x1920])
'This is a line that includes a behaviour which
| breaks this line beforehand.

**When the user viewport switched back to 1080x1920, should the line break remain intact (check above) or move back up?**
'This is a line that includes a behaviour which breaks this line beforehand. |'

**Comment by Nikica-Luger** [comment]
I just checked that, and it seems that it **moves back up**, which is not that bad. The user will probablz not be suprised by rearrangement of the lines when changing the viewport, as one can expect visual changes when changing the viewport.

**Comment by Nikica-Luger** [comment]
If there would be a solution to manually check remaining span-length and add an explicit line break, this would not be necessary. Maybe by using `preStringTyped`. I'm just not sure how to check the remaining length of the span, and also not sure how to calculate the space the next word will need. (Assuming no monospace font and additional complexities like a bunch of CSS rules applied on the font..)

**Comment by Nikica-Luger** [comment]
I think whether this feature is useful might be discussable. But one thing is for sure: A word should not **be printed on line 1, then on line 2, then again on line** 1. This happens when the word **with** cursors does not fit into line 1, but the word **without cursor does**. Then the word is moved into the second line, then when the cursor goes one line down, the word is **moved back into the first line.**

**Comment by mattboldt** [comment]
It sounds like the behavior you described (word teleport) is how it works in any text editor. Since this plugin is supposed to emulate typing, I don't think this is something I'd like to add. When words are being typed, the eyes follow. I think it'd be _more_ confusing if, mid-type (with more space left), it jumped down a line.
