### ISSUE TITLE
Type multiple characters at a time

### ISSUE THREAD

**Issue by taylankasap** [mattboldt/typed.js#402]
### Description

Since typed.js uses setTimeout we can't make it type faster than 0ms delay. So I was thinking what if we make it type more than one character at a time, that would make it look fast. It turns out there already is a `numChars` variable. Increasing it indeed makes the typing look faster. But see below for the problem.

### Demo
http://jsfiddle.net/taylankasap/sxh2r761/5/

### Steps to Reproduce

1. Change `numChars` to something greater than 1
2. Test it with multiple strings

**Expected behavior:** When `numChars` is changed to 2 for example, type 2 characters at a time and remove 2 characters at a time. Also multiple strings should keep working.

**Actual behavior:** Multiple strings doesn't work for some reason if I change the `numChars` in line 218 (in the jsfiddle) to something greater than 1.

**Reproduces how often:** 100%

**Comment by mattboldt** [comment]
`numChars` isn't part of the public API, so it's not supposed to be changed. It's dynamically updated based on what type of string is being typed: e.g. an html tag that needs to print all at once instead of 1 char at a time. Since you updated it to 4, it must be tripping up on that 2nd html element.

In order to achieve what you're looking for, you'd need to leverage the `numChar` variable, but instead of arbitrarily setting it to 4, it would need to be the length of the characters you want to type (excluding existing logic for html, etc).

Feel free to open a PR if you'd like to add the feature!
