### ISSUE TITLE
Crashs whole website

### ISSUE THREAD

**Issue by OliverPetrovic** [mattboldt/typed.js#411]
### Description

When I put and character ("&") to typed array it will crash website, i don't know why ._.

### Demo

just try this:
`strings: ["Hello (this works)", "You & me (here it crashs)"],`

### Steps to Reproduce

1. Make basic typed.js setup
2. Put "&" character into an array
3. Open in browser

**Expected behavior:** Only make typed.js effect

**Actual behavior:** when will come typed.js cursor to "&" symbol, it crashs.

**Reproduces how often:** 100%, I don't know how to fix it

**Comment by mattboldt** [comment]
If you're using the `contentType: 'html'` setting, then it's expecting HTML characters. The `&` is the beginning of an HTML character, so that's why it's crashing. I should probably fix the crashing bit, but for now you can either use `&amp;` to render an ampersand, or you could set `contentType: 'text'`
