### ISSUE TITLE
Carets appear incorrectly in <input>s

### ISSUE THREAD

**Issue by redbrain** [mattboldt/typed.js#464]
### Description

Carets will not appear correctly/at all in an input element when done via Typed.js

### Demo
https://jsfiddle.net/35qxkyrs/

### Steps to Reproduce

1. Create a Typed on an input (attr can be value, placeholder, it doesnt seem to matter)
2. Include carets in  the strings.

**Expected behavior:** Carets appear as typed in the strings.

**Actual behavior:** It and the character next to it disappear, or it stays as an '&Hat;' if entered that way

**Reproduces how often:** 100% of the time

### Additional Information

Chrome/86.0.4240.111 on Linux x64.

**Comment by mattboldt** [comment]
Thank you for the detailed issue! Unfortunately, because it's an input, I don't think you can use HTML entities like that. And then, because `^` is an escape character for delaying the animation, it won't render properly. Simplest solution that comes to mind would be some kind of setting to disable the `^` delay functionality and let it type it out normally.
