### ISSUE TITLE
Simply doesn't work. (TypeError: self.el is null)

### ISSUE THREAD

**Issue by hrqmonteiro** [mattboldt/typed.js#480]
![2021-04-19_16-50](https://user-images.githubusercontent.com/17055027/115294902-b4533000-a148-11eb-889e-8671c1e096c2.png)

Code:

```
import Typed from "typed.js";
import Navbar from "./components/UI/Navbar";

const App = () => {
  const options = {
    strings: ["<i>First</i> sentence.", "&amp; a second sentence."],
    typeSpeed: 40,
    startDelay: 1000,
    typeSpeed: 50,
    backSpeed: 10,
    smartBackspace: true,
    backDelay: 1500,
    loop: true,
    shuffle: true,
  };

  const typed = new Typed(".element", options);

  return (
    <div>
      <Navbar />
      <span className="element">{typed}</span>
    </div>
  );
};

export default App;
```

**Comment by Yash-Singh1** [comment]
`self.el` will be `null` when `document.querySelector` returns `null`. That will happen only when no element exists with the class name `element`. Maybe trying to change `className` to `class` might work. Another alternative would be to change the selector to `[className="element"]`.

**Comment by hrqmonteiro** [comment]
I can't change `className` to `class` since i'm on React, my dude.

And it simply didn't work back then. I'm trying on a new project made in NextJs and it doesn't work either. It doesn't recognize the `new Typed` even though i import it using `import Typed from "typed.js` installing through yarn, or if i use cdn it doesn't work either.

```
import { Container } from "react-bootstrap";
import "typed.js";

const Slider = () => {
  const options = {
    strings: ["<i>First</i> sentence.", "&amp; a second sentence."],
    typeSpeed: 40,
  };

  const typed = new Typed(".element", {
    strings: ["First sentence.", "Second sentence."],
    typeSpeed: 30,
  });

  return (
    <Container fluid className="px-0 py-0">
      <div className="slider">
        <h1 className="element">
          Há 30 anos no mercado, dando vida à sua joia
        </h1>

        <h2>Test</h2>
      </div>
    </Container>
  );
};

export default Slider;
```

![2021-05-30_13-09](https://user-images.githubusercontent.com/17055027/120111429-50a92300-c148-11eb-94cb-64d7896ffc48.png)

I simply can't use it. Doesn't work.

**Comment by mattboldt** [comment]
You're working with a stateless function component, which does not behave the same way vanilla javascript would in the browser. Here's an updated demo using React hooks: https://jsfiddle.net/mattboldt/60h9an7y/43/

One big difference here is that you cannot rely on a class name or ID because Typed will attempt to find it on the current `document`, which does not exist in the context of react. Furthermore, you must initialize it in a component lifecycle hook. The code you have here would initialize a new instance of Typed on each render, which would not work.

I'll update the readme to include the new demo
