### ISSUE TITLE
preStringTyped

### ISSUE THREAD

**Issue by lewiscowleschipuk** [mattboldt/typed.js#499]
### Description

Using `preStringTyped` with  this library, the `arrayPos` never goes beyond 3.

### Demo

https://staging.webflow.io/advanced-assets

### Steps to Reproduce

```
<div class="typed-text"></div>
<script src=“https://cdn.jsdelivr.net/npm/typed.js@2.0.9”></script>
    <script>
    	const typeWordsWithColors = {
             'Watches': 'rgb(114, 68, 237)',
             'Art': 'green',
             'Cars': 'red',
             'Wine': '#0099ff',
             'Whisky': 'white',
             '': ''
        };
        const wordsToArray = Object.entries(typeWordsWithColors);
        const elementSelector = '.typed-text';
        var typed4 = new Typed(elementSelector, {
            strings: wordsToArray.map(entry => entry[0]),
            typeSpeed: 75,
            backSpeed: 25,
            bindInputFocusEvents: true,
            loop: true,
            cursorChar: '_',
            backDelay: 1000,
            startDelay: 1000,
            preStringTyped: (arrayPos, self) => {
                console.log("changed", {arrayPos, wordsToArray}); // this was just to see if you were starting from index 1 or modifying the word-list
                document.querySelector(elementSelector).style.color = wordsToArray[arrayPos][1];
            },
        });
    </script>
```

**Expected behavior:** [What you expect to happen]

arrayPos goes 0, 1, 2, 3, 4, 5

**Actual behavior:** [What actually happens]

arrayPos stops at 3...

**Reproduces how often:** [What percentage of the time does it reproduce?]

Consistently in Chrome (latest)

### Additional Information

Our designer asked if this was web-flow... It doesn't seem to be.

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by Lewiscowles1986** [comment]
I believe I've solved this and the cause is... Well, strange! https://codepen.io/Lewiscowles1986/pen/KKZRbKb

I made a codepen for our designer at work to play with, and last night I thought I'd see if I could find where this was going wrong by forking that and cloning this repo locally.

The problem seems to be that the two last items begin with the same letter, so this tries to do a clever backspace trick, which leaves the W from wine, for Whisky (I'm sure it's Whiskey). This is what was preventing arrayPos from updating.

**Comment by Lewiscowles1986** [comment]
Confirmed that `smartBackspace: false,` solves this.

So if you hit this problem, and don't fancy changing the library, either 

* Coordinate so that strings do not share common prefixes, or otherwise get picked up by "smart" backspace.
* Turn off "smart" backspace using `smartBackspace: false,` when configuring your `Typed` instance.

**Comment by Lewiscowles1986** [comment]
This should not be closed. It's an ongoing issue because of the design of the library. I've had no conversation with any maintainer.
