### ISSUE TITLE
is it possible to set typeSpeed faster than 0 ?

### ISSUE THREAD

**Issue by kegilko** [mattboldt/typed.js#520]
First of all, thanks for this amasing library !

I'm looking for a way to type very, very quickly
I set attribute typeSpeed to 0, but its too slow for what I want. 

Is there a way to go faster than '0' ? (I tried a negative value but the result is a same as the value 0)

Thanks for any help :)

**Comment by mattboldt** [comment]
I ran into this issue today -- even with a negative value, it seems like there's a limit on how fast the settimeout loop works. An alternative you could consider is wrapping certain strings like
```js
strings: ["type `these words` `all at once`"]
```
this will make it display "these words" and "all at once" all at once instead of typing each character. This will make it appear more rapidly.

Besides that, I'm not sure of a good fix to increase the animation speed
