### ISSUE TITLE
First string typed is not showing

### ISSUE THREAD

**Issue by stefankempf** [mattboldt/typed.js#526]
### Description

The first string I use for the typewriter animation is not showing.

### Demo
https://codepen.io/stefankempf/pen/JjBjEWq

### Workaround
Use an empty span as first element.

Same as https://github.com/mattboldt/typed.js/issues/518

**Comment by digisomni** [comment]
I am getting this issue too.

**Comment by mattboldt** [comment]
huh, this is odd. Looks like it only happens if there is extra space in the typed element at the start. In your codepen, when I updated it to `<span id="typed"></span>`, it worked correctly 🤔

**Comment by mattboldt** [comment]
Ah, I know what's happening. If you start with an element like this:
```html
<span id="typed">Some static text</span>
```
typed.js will detect "Some static text" exists, and it will backspace it as part of the animation. However, due to a bug, it now things that it needs to move forward to the "next" string to animate. It skips the 1st one because it thinks it's already backspaced it.

Not sure of good a fix right now, but I'll put some thought into it.

**Comment by mattboldt** [comment]
Fixed with the latest release!
