### ISSUE TITLE
IE9 Support

### ISSUE THREAD

**Issue by tjsreece** [mattboldt/typed.js#83]
IE9 does not support CSS3 @keyframes, so therefore the cursor animation will not work. Is there anyway the cursor could be built into the jQuery?

**Comment by mattboldt** [comment]
I'd like to keep the library very lightweight and not rely on a heavy jQuery opacity animation. That's why I left the CSS out and let users take it from the readme and customize it as they please. You could target the element and write your own jQuery, though. Something like a loop with `$(".typed-cursor").fadeIn()` and `$(".typed-cursor").fadeOut()`.
